name: stm
description: A new Flutter project for Storage Task Manager.
version: 0.1.0-alpha

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add other dependencies here
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Add assets here
  assets:
    - v0.1.0-alpha/ext_data/workers.json